name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:
  environment: Kubernetes
  runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    
    - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply nginx.yaml
