name: build-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    environment: Dockerhub
    env:
      user: ${{ secrets.DOCKERHUB_USERNAME }}
      pass: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: $user
          password: $pass
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: $user/myapp:v1
