
name: build-push-image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    environment: Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push Docker image
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}:myapp1
        tags: v1, latest
        registry: https://hub.docker.com/
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
